In [33]:
import pandas as pd
matches = pd.read_csv("PLmatches.csv",index_col=0)
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3.0,0.0,Burnley,...,Match Report,NaN,17.0,8.0,13.9,0.0,0,0,2023,Manchester City
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1.0,0.0,Newcastle Utd,...,Match Report,NaN,14.0,4.0,17.9,0.0,0,0,2023,Manchester City
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Sheffield Utd,...,Match Report,NaN,29.0,9.0,17.3,2.0,0,1,2023,Manchester City
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5.0,1.0,Fulham,...,Match Report,NaN,6.0,4.0,14.8,0.0,1,1,2023,Manchester City
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,West Ham,...,Match Report,NaN,29.0,13.0,16.4,1.0,0,0,2023,Manchester City

In [34]:
matches.shape

(3976, 27)

In [35]:
matches["team"].value_counts()

team
Manchester City             199
Manchester United           199
Everton                     199
Arsenal                     199
Crystal Palace              199
Chelsea                     199
Wolverhampton Wanderers     199
Brighton and Hove Albion    199
Newcastle United            199
Liverpool                   199
West Ham United             198
Tottenham Hotspur           198
Leicester City              190
Southampton                 190
Burnley                     161
Aston Villa                 160
Bournemouth                 123
Fulham                      122
Watford                     114
Leeds United                114
Brentford                    85
Sheffield United             85
Norwich City                 76
Nottingham Forest            47
West Bromwich Albion         38
Cardiff City                 38
Huddersfield Town            38
Luton Town                    9
Name: count, dtype: int64

In [36]:
matches["round"].value_counts()

round
Matchweek 1     120
Matchweek 3     120
Matchweek 4     120
Matchweek 5     120
Matchweek 6     120
Matchweek 7     120
Matchweek 8     120
Matchweek 2     120
Matchweek 9     116
Matchweek 33    100
Matchweek 26    100
Matchweek 27    100
Matchweek 29    100
Matchweek 30    100
Matchweek 31    100
Matchweek 36    100
Matchweek 34    100
Matchweek 28    100
Matchweek 35    100
Matchweek 24    100
Matchweek 37    100
Matchweek 32    100
Matchweek 25    100
Matchweek 21    100
Matchweek 12    100
Matchweek 23    100
Matchweek 22    100
Matchweek 20    100
Matchweek 19    100
Matchweek 18    100
Matchweek 17    100
Matchweek 16    100
Matchweek 15    100
Matchweek 14    100
Matchweek 13    100
Matchweek 11    100
Matchweek 10    100
Matchweek 38    100
Name: count, dtype: int64

In [37]:
#data cleaning

In [38]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [39]:
matches["date"] = pd.to_datetime(matches["date"])
matches.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                       int64
pkatt                    int64
season                   int64
team                    object
dtype: object

In [40]:
#creating predictors for ML
matches["venue_code"] = matches["venue"].astype("category").cat.codes #convert string to categorial data and then to integers
matches["opp_code"] = matches["opponent"].astype("category").cat.codes #give each team a code
matches["hour"] = matches["time"].str.replace(":.+","", regex=True).astype("int") #regular expression replace : with ""
matches["day_code"] = matches["date"].dt.dayofweek
matches["target"] = (matches["result"] == "W").astype("int") #W~True and L&D ~ false

In [41]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3.0,0.0,Burnley,...,0.0,0,0,2023,Manchester City,0,5,20,4,1
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1.0,0.0,Newcastle Utd,...,0.0,0,0,2023,Manchester City,1,18,20,5,1
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Sheffield Utd,...,2.0,0,1,2023,Manchester City,0,21,14,6,1
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5.0,1.0,Fulham,...,0.0,1,1,2023,Manchester City,1,10,15,5,1
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,West Ham,...,1.0,0,0,2023,Manchester City,0,26,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,2019-04-13,12:30,Premier League,Matchweek 34,Sat,Away,L,0.0,4.0,Tottenham,...,1.0,0,0,2021,Huddersfield Town,0,23,12,5,0
36,2019-04-20,15:00,Premier League,Matchweek 35,Sat,Home,L,1.0,2.0,Watford,...,1.0,0,0,2021,Huddersfield Town,1,24,15,5,0
37,2019-04-26,20:00,Premier League,Matchweek 36,Fri,Away,L,0.0,5.0,Liverpool,...,0.0,0,0,2021,Huddersfield Town,0,14,20,4,0
38,2019-05-05,14:00,Premier League,Matchweek 37,Sun,Home,D,1.0,1.0,Manchester Utd,...,1.0,0,0,2021,Huddersfield Town,1,17,14,6,0
39,2019-05-12,15:00,Premier League,Matchweek 38,Sun,Away,D,1.0,1.0,Southampton,...,0.0,0,0,2021,Huddersfield Town,0,22,15,6,0

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [44]:
#subset
train = matches[matches["date"] <'2023-01-01']
test = matches[matches["date"] >'2023-01-01']
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [45]:
rf.fit(train[predictors],train["target"]) #fit to train predictors and predict target

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [46]:
preds = rf.predict(test[predictors])

In [47]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(test["target"], preds)
acc

0.6026490066225165

In [48]:
#create DF that will combine actual(target) and predicted values(preds)
combined = pd.DataFrame(dict(actual=test["target"], prediction=preds))

In [49]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])

prediction    0   1
actual
0           291  79
1           161  73

In [50]:
from sklearn.metrics import precision_score
precision_score(test["target"],preds)

0.48026315789473684

In [51]:
#Improving precison with rolling averages
grouped_matches = matches.groupby("team") #split matches df and group by team(i.e, one df for each team)
group = grouped_matches.get_group("Manchester United")
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2023-08-14,20:00,Premier League,Matchweek 1,Mon,Home,W,1.0,0.0,Wolves,...,0.0,0,0,2023,Manchester United,1,27,20,0,1
1,2023-08-19,17:30,Premier League,Matchweek 2,Sat,Away,L,0.0,2.0,Tottenham,...,1.0,0,0,2023,Manchester United,0,23,17,5,0
2,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,W,3.0,2.0,Nott'ham Forest,...,0.0,1,1,2023,Manchester United,1,20,15,5,1
3,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Away,L,1.0,3.0,Arsenal,...,0.0,0,0,2023,Manchester United,0,0,16,6,0
4,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Home,L,1.0,3.0,Brighton,...,1.0,0,0,2023,Manchester United,1,4,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,2019-04-21,13:30,Premier League,Matchweek 35,Sun,Away,L,0.0,4.0,Everton,...,1.0,0,0,2021,Manchester United,0,9,13,6,0
49,2019-04-24,20:00,Premier League,Matchweek 31,Wed,Home,L,0.0,2.0,Manchester City,...,1.0,0,0,2021,Manchester United,1,16,20,2,0
50,2019-04-28,16:30,Premier League,Matchweek 36,Sun,Home,D,1.0,1.0,Chelsea,...,1.0,0,0,2021,Manchester United,1,7,16,6,0
51,2019-05-05,14:00,Premier League,Matchweek 37,Sun,Away,D,1.0,1.0,Huddersfield,...,2.0,0,0,2021,Manchester United,0,11,14,6,0
52,2019-05-12,15:00,Premier League,Matchweek 38,Sun,Home,L,0.0,2.0,Cardiff City,...,1.0,0,0,2021,Manchester United,1,6,15,6,0

In [52]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3,closed='left').mean() #to exclude current week closed =left
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols) #remove rows with missing values
    return group

In [53]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols =[f"{c}_rolling" for c in cols]
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [54]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
3,2018-09-02,16:00,Premier League,Matchweek 4,Sun,Away,W,2.0,0.0,Burnley,...,6,1,1.333333,2.333333,12.666667,4.000000,19.933333,0.333333,0.666667,0.666667
4,2018-09-15,17:30,Premier League,Matchweek 5,Sat,Away,W,2.0,1.0,Watford,...,5,1,1.333333,2.000000,17.000000,5.000000,19.133333,0.333333,0.333333,0.666667
6,2018-09-22,15:00,Premier League,Matchweek 6,Sat,Home,D,1.0,1.0,Wolves,...,5,0,1.333333,1.333333,17.333333,6.333333,17.200000,0.333333,0.000000,0.333333
8,2018-09-29,12:30,Premier League,Matchweek 7,Sat,Away,L,1.0,3.0,West Ham,...,5,0,1.666667,0.666667,14.666667,6.666667,19.200000,1.000000,0.000000,0.333333
10,2018-10-06,17:30,Premier League,Matchweek 8,Sat,Home,W,3.0,2.0,Newcastle Utd,...,5,1,1.333333,1.666667,11.000000,5.333333,19.533333,1.333333,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Home,L,1.0,3.0,Brighton,...,5,0,1.333333,2.333333,16.333333,5.333333,17.466667,0.333333,0.333333,0.333333
6,2023-09-23,20:00,Premier League,Matchweek 6,Sat,Away,W,1.0,0.0,Burnley,...,5,1,1.666667,2.666667,13.666667,4.666667,18.466667,0.333333,0.333333,0.333333
8,2023-09-30,15:00,Premier League,Matchweek 7,Sat,Home,L,0.0,1.0,Crystal Palace,...,5,0,1.000000,2.000000,11.666667,3.333333,16.700000,0.333333,0.000000,0.000000
10,2023-10-07,15:00,Premier League,Matchweek 8,Sat,Home,W,2.0,1.0,Brentford,...,5,1,0.666667,1.333333,14.666667,3.666667,16.366667,0.333333,0.000000,0.000000
11,2023-10-21,20:00,Premier League,Matchweek 9,Sat,Away,W,2.0,1.0,Sheffield Utd,...,5,1,1.000000,0.666667,17.000000,5.000000,16.266667,0.333333,0.000000,0.000000

In [55]:
#matches df group by team and one df for each team
#apply rolling_avaerages function to each team
matches_rolling =matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))
matches_rolling = matches_rolling.droplevel('team') #drop extra index levels
matches_rolling.index = range(matches_rolling.shape[0]) #unique value for index
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2018-09-02,13:30,Premier League,Matchweek 4,Sun,Away,W,3.0,2.0,Cardiff City,...,6,1,1.666667,2.000000,13.666667,6.333333,18.166667,0.333333,0.0,0.0
1,2018-09-15,15:00,Premier League,Matchweek 5,Sat,Away,W,2.0,1.0,Newcastle Utd,...,5,1,2.666667,2.000000,16.333333,9.000000,17.300000,0.333333,0.0,0.0
2,2018-09-23,16:00,Premier League,Matchweek 6,Sun,Home,W,2.0,0.0,Everton,...,6,1,2.666667,1.333333,15.333333,7.666667,17.333333,0.666667,0.0,0.0
3,2018-09-29,15:00,Premier League,Matchweek 7,Sat,Home,W,2.0,0.0,Watford,...,5,1,2.333333,1.000000,12.666667,6.000000,17.133333,0.333333,0.0,0.0
4,2018-10-07,12:00,Premier League,Matchweek 8,Sun,Away,W,5.0,1.0,Fulham,...,6,1,2.000000,0.333333,10.000000,3.000000,16.666667,0.333333,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3881,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Home,L,1.0,3.0,Liverpool,...,5,0,1.333333,2.333333,13.000000,3.666667,16.700000,0.333333,0.0,0.0
3882,2023-09-23,15:00,Premier League,Matchweek 6,Sat,Away,D,1.0,1.0,Luton Town,...,5,0,1.333333,2.000000,11.333333,2.666667,17.566667,0.333333,0.0,0.0
3883,2023-09-30,15:00,Premier League,Matchweek 7,Sat,Home,W,2.0,1.0,Manchester City,...,5,1,1.333333,2.333333,8.666667,3.000000,13.966667,0.000000,0.0,0.0
3884,2023-10-08,14:00,Premier League,Matchweek 8,Sun,Home,D,1.0,1.0,Aston Villa,...,6,0,1.333333,1.666667,5.666667,2.000000,12.366667,0.000000,0.0,0.0
3885,2023-10-21,15:00,Premier League,Matchweek 9,Sat,Away,W,2.0,1.0,Bournemouth,...,5,1,1.333333,1.000000,4.666667,2.333333,11.466667,0.000000,0.0,0.0

In [56]:
#Retrain ML model

def make_predictions(data, predictors):
    train = data[data["date"] <'2023-01-01']
    test = data[data["date"] >'2023-01-01']
    rf.fit(train[predictors],train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], prediction=preds), index=test.index)
    precision = precision_score(test["target"],preds) 
    return combined, precision

In [57]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)
precision

0.5925925925925926

In [58]:
combined

      actual  prediction
165        0           1
166        1           0
167        1           0
168        0           1
169        0           1
...      ...         ...
3881       0           0
3882       0           0
3883       1           0
3884       0           0
3885       1           0

[601 rows x 2 columns]

In [59]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [60]:
combined

,actual,prediction,date,team,opponent,result
165,0,1,2023-01-03,Arsenal,Newcastle Utd,D
166,1,0,2023-01-15,Arsenal,Tottenham,W
167,1,0,2023-01-22,Arsenal,Manchester Utd,W
168,0,1,2023-02-04,Arsenal,Everton,L
169,0,1,2023-02-11,Arsenal,Brentford,D
...,...,...,...,...,...,...
3881,0,0,2023-09-16,Wolverhampton Wanderers,Liverpool,L
3882,0,0,2023-09-23,Wolverhampton Wanderers,Luton Town,D
3883,1,0,2023-09-30,Wolverhampton Wanderers,Manchester City,W
3884,0,0,2023-10-08,Wolverhampton Wanderers,Aston Villa,D
3885,1,0,2023-10-21,Wolverhampton Wanderers,Bournemouth,W

In [61]:
class MissingDict(dict):
    __missing__ = lambda self, key: key
    
map_values ={
    "Brighton and Hove Albion": "Brighton",
    "Manchester United" : "Manchester Utd",
    "Wolverhampton Wanderers" : "Wolves",
    "Newcastle United" : "Newcastle Utd",
    "Tottenham Hotspur" : "Tottenham",
    "West Ham United" : "West Ham"
}

mapping = MissingDict(**map_values)

In [62]:
combined["new_team"] = combined["team"].map(mapping)

In [63]:
combined

,actual,prediction,date,team,opponent,result,new_team
165,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal
166,1,0,2023-01-15,Arsenal,Tottenham,W,Arsenal
167,1,0,2023-01-22,Arsenal,Manchester Utd,W,Arsenal
168,0,1,2023-02-04,Arsenal,Everton,L,Arsenal
169,0,1,2023-02-11,Arsenal,Brentford,D,Arsenal
...,...,...,...,...,...,...,...
3881,0,0,2023-09-16,Wolverhampton Wanderers,Liverpool,L,Wolves
3882,0,0,2023-09-23,Wolverhampton Wanderers,Luton Town,D,Wolves
3883,1,0,2023-09-30,Wolverhampton Wanderers,Manchester City,W,Wolves
3884,0,0,2023-10-08,Wolverhampton Wanderers,Aston Villa,D,Wolves
3885,1,0,2023-10-21,Wolverhampton Wanderers,Bournemouth,W,Wolves